"""Expand the evidence knowledge base from authoritative public APIs.

Sources used by this script:
    - PubMed E-utilities (NCBI)
    - Europe PMC REST API
    - ClinicalTrials.gov Data API v2

The script never invents article URLs. URLs are generated by the existing
ingest adapters from returned PMID/NCT/Europe PMC identifiers.

Run from the evidence-assistant-mvp directory:
    python scripts/expand_kb.py --target-chunks 500
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# Allow running as `python scripts/expand_kb.py` from the project root.
ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.config import get_settings
from src.ingest import (
    dedupe_by_doi_or_title,
    export_ingest_report,
    merge_docs,
    save_docs,
)
from src.ingest.clinicaltrials import ingest_clinicaltrials
from src.ingest.europepmc import ingest_europepmc
from src.ingest.local_docs import ingest_local
from src.ingest.pubmed import ingest_pubmed
from src.kb.chunking import docs_to_chunks, merge_tiny_chunks, validate_chunk_traceability
from src.kb.store import EvidenceStore, export_store_stats
from src.kb.wiki import generate_wiki_pages

logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
logger = logging.getLogger(__name__)


# These queries stay within the project scope: hypertension, lipids, diabetes,
# cardiovascular prevention, dietary patterns, sodium, and lifestyle treatment.
# They are search expressions only; article links come from API identifiers.
PUBMED_QUERIES = [
    'hypertension[MeSH Terms] AND antihypertensive agents[MeSH Terms] AND (guideline[Publication Type] OR practice guideline[Publication Type]) AND hasabstract[text]',
    'hypertension[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND (systematic review[Title/Abstract] OR meta-analysis[Publication Type]) AND hasabstract[text]',
    'hypertension[MeSH Terms] AND blood pressure[Title/Abstract] AND lifestyle[Title/Abstract] AND hasabstract[text]',
    'hypertension[MeSH Terms] AND sodium, dietary[MeSH Terms] AND (systematic review[Title/Abstract] OR randomized controlled trial[Publication Type]) AND hasabstract[text]',
    'hypertension[MeSH Terms] AND diet, sodium-restricted[MeSH Terms] AND hasabstract[text]',
    'hypertension[MeSH Terms] AND diet therapy[MeSH Terms] AND hasabstract[text]',
    'hypertension[MeSH Terms] AND exercise[MeSH Terms] AND blood pressure[Title/Abstract] AND hasabstract[text]',
    'hypertension[MeSH Terms] AND weight loss[MeSH Terms] AND blood pressure[Title/Abstract] AND hasabstract[text]',
    'hypertension[MeSH Terms] AND potassium[MeSH Terms] AND blood pressure[Title/Abstract] AND hasabstract[text]',
    'hyperlipidemias[MeSH Terms] AND hydroxymethylglutaryl-CoA reductase inhibitors[MeSH Terms] AND (guideline[Publication Type] OR meta-analysis[Publication Type]) AND hasabstract[text]',
    'hyperlipidemias[MeSH Terms] AND cholesterol, LDL[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND hasabstract[text]',
    'hyperlipidemias[MeSH Terms] AND diet therapy[MeSH Terms] AND hasabstract[text]',
    'hyperlipidemias[MeSH Terms] AND lifestyle[Title/Abstract] AND cardiovascular risk[Title/Abstract] AND hasabstract[text]',
    'hydroxymethylglutaryl-CoA reductase inhibitors[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND randomized controlled trial[Publication Type] AND hasabstract[text]',
    'diabetes mellitus, type 2[MeSH Terms] AND diet therapy[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND hasabstract[text]',
    'diabetes mellitus, type 2[MeSH Terms] AND lifestyle[Title/Abstract] AND cardiovascular risk[Title/Abstract] AND hasabstract[text]',
    'diet, mediterranean[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND (systematic review[Title/Abstract] OR randomized controlled trial[Publication Type]) AND hasabstract[text]',
    'diet, dash[Title/Abstract] AND blood pressure[Title/Abstract] AND hasabstract[text]',
    'dietary patterns[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND meta-analysis[Publication Type] AND hasabstract[text]',
    'diet therapy[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND systematic review[Title/Abstract] AND hasabstract[text]',
    'sodium, dietary[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND hasabstract[text]',
    'life style[MeSH Terms] AND cardiovascular diseases[MeSH Terms] AND meta-analysis[Publication Type] AND hasabstract[text]',
]

EUROPEPMC_QUERIES = [
    "OPEN_ACCESS:Y AND hypertension AND (guideline OR systematic review)",
    "OPEN_ACCESS:Y AND hypertension AND cardiovascular risk",
    "OPEN_ACCESS:Y AND hypertension AND sodium",
    "OPEN_ACCESS:Y AND hypertension AND diet",
    "OPEN_ACCESS:Y AND hypertension AND exercise",
    "OPEN_ACCESS:Y AND hypertension AND weight loss",
    "OPEN_ACCESS:Y AND hyperlipidemia AND statin",
    "OPEN_ACCESS:Y AND hyperlipidemia AND diet",
    "OPEN_ACCESS:Y AND LDL cholesterol AND cardiovascular",
    "OPEN_ACCESS:Y AND type 2 diabetes AND diet",
    "OPEN_ACCESS:Y AND Mediterranean diet AND cardiovascular",
    "OPEN_ACCESS:Y AND DASH diet AND blood pressure",
    "OPEN_ACCESS:Y AND dietary sodium AND blood pressure",
    "OPEN_ACCESS:Y AND lifestyle intervention AND cardiovascular",
]

TRIAL_CONDITIONS = [
    "Hypertension",
    "Hypertension Dietary Intervention",
    "Hypertension Sodium Reduction",
    "Hypertension Exercise",
    "Hyperlipidemia",
    "Hyperlipidemia Statin",
    "Type 2 Diabetes Mellitus Dietary Intervention",
    "Mediterranean Diet Cardiovascular",
    "DASH Diet Blood Pressure",
    "Dietary Sodium Blood Pressure",
]


def _annotate_query(docs, source: str, queries: list[str]):
    """保存采集批次信息，不改变 EvidenceDoc 对外字段。"""
    query_text = " | ".join(queries)
    out = []
    for doc in docs:
        extra = dict(doc.extra or {})
        extra["collection_batch"] = "expanded_authoritative_sources"
        extra["collection_source"] = source
        extra["collection_query"] = query_text
        out.append(doc.model_copy(update={"extra": extra}))
    return out


def expand_knowledge_base(
    *,
    target_chunks: int = 500,
    pubmed_retmax: int = 35,
    europepmc_page_size: int = 25,
    trial_page_size: int = 20,
) -> dict:
    """Collect, normalize, index, and verify an expanded evidence corpus."""
    settings = get_settings()
    retrieved_at = datetime.now(timezone.utc).isoformat()

    local_docs = ingest_local(include_seed=True)
    pubmed_docs = _annotate_query(
        ingest_pubmed(queries=PUBMED_QUERIES, retmax_per_query=pubmed_retmax),
        "pubmed",
        PUBMED_QUERIES,
    )
    europepmc_docs = _annotate_query(
        ingest_europepmc(queries=EUROPEPMC_QUERIES, page_size=europepmc_page_size),
        "europepmc",
        EUROPEPMC_QUERIES,
    )
    trial_docs = _annotate_query(
        ingest_clinicaltrials(conditions=TRIAL_CONDITIONS, page_size=trial_page_size),
        "clinicaltrials",
        TRIAL_CONDITIONS,
    )

    # Keep each raw source separately so the data lineage is inspectable.
    save_docs(local_docs, settings.raw_path / "local_docs.json")
    save_docs(pubmed_docs, settings.raw_path / "pubmed.json")
    save_docs(europepmc_docs, settings.raw_path / "europepmc.json")
    save_docs(trial_docs, settings.raw_path / "clinicaltrials.json")

    docs = dedupe_by_doi_or_title(
        merge_docs(local_docs, pubmed_docs, trial_docs, europepmc_docs)
    )
    save_docs(docs, settings.processed_path / "documents.json")
    export_ingest_report(docs, settings.processed_path / "ingest_report.md")

    wiki_docs = generate_wiki_pages(docs)
    save_docs(wiki_docs, settings.processed_path / "wiki_docs.json")
    all_docs = dedupe_by_doi_or_title(merge_docs(docs, wiki_docs))
    save_docs(all_docs, settings.processed_path / "documents_with_wiki.json")

    chunks = merge_tiny_chunks(docs_to_chunks(all_docs))
    trace = validate_chunk_traceability(chunks)
    if not trace["ok"]:
        raise RuntimeError(f"Chunk traceability failed: {trace}")

    store = EvidenceStore()
    store.reset()
    store.upsert_chunks(chunks)
    stats = export_store_stats(settings.processed_path / "store_stats.json")
    actual_chunks = int(stats.get("count", store.count()))
    if actual_chunks < target_chunks:
        raise RuntimeError(
            f"Expanded knowledge base has {actual_chunks} chunks, below target {target_chunks}. "
            "Increase the API page sizes or add reviewed queries before presenting the result."
        )

    manifest = {
        "retrieved_at_utc": retrieved_at,
        "scope": [
            "hypertension",
            "hyperlipidemia",
            "statin",
            "type 2 diabetes",
            "cardiovascular prevention",
            "Mediterranean diet",
            "DASH diet",
            "dietary sodium",
            "lifestyle intervention",
        ],
        "authoritative_sources": [
            {
                "name": "PubMed E-utilities",
                "endpoint": "https://eutils.ncbi.nlm.nih.gov/entrez/eutils",
                "api_documentation": "https://www.ncbi.nlm.nih.gov/books/NBK25501/",
                "query_count": len(PUBMED_QUERIES),
                "retmax_per_query": pubmed_retmax,
                "documents": len(pubmed_docs),
            },
            {
                "name": "Europe PMC REST API",
                "endpoint": "https://www.ebi.ac.uk/europepmc/webservices/rest/search",
                "api_documentation": "https://europepmc.org/RestfulWebService",
                "query_count": len(EUROPEPMC_QUERIES),
                "page_size": europepmc_page_size,
                "documents_after_oa_filter": len(europepmc_docs),
            },
            {
                "name": "ClinicalTrials.gov Data API v2",
                "endpoint": "https://clinicaltrials.gov/api/v2/studies",
                "api_documentation": "https://clinicaltrials.gov/data-api/api",
                "condition_count": len(TRIAL_CONDITIONS),
                "page_size": trial_page_size,
                "documents": len(trial_docs),
            },
        ],
        "counts": {
            "local_documents": len(local_docs),
            "deduplicated_evidence_documents": len(docs),
            "wiki_documents": len(wiki_docs),
            "all_documents_with_wiki": len(all_docs),
            "chunks": actual_chunks,
        },
        "files": {
            "raw": [
                "data/raw/local_docs.json",
                "data/raw/pubmed.json",
                "data/raw/europepmc.json",
                "data/raw/clinicaltrials.json",
            ],
            "processed": [
                "data/processed/documents.json",
                "data/processed/documents_with_wiki.json",
                "data/processed/wiki_docs.json",
                "data/processed/ingest_report.md",
                "data/processed/store_stats.json",
                "data/processed/store_stats.md",
                "data/processed/expansion_manifest.json",
            ],
        },
    }
    manifest_path = settings.processed_path / "expansion_manifest.json"
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")
    logger.info(
        "Expanded KB ready: %d evidence docs, %d docs with wiki, %d chunks",
        len(docs),
        len(all_docs),
        actual_chunks,
    )
    logger.info("Expansion manifest -> %s", manifest_path)
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser(description="Expand evidence KB from authoritative public APIs")
    parser.add_argument("--target-chunks", type=int, default=500)
    parser.add_argument("--pubmed-retmax", type=int, default=35)
    parser.add_argument("--europepmc-page-size", type=int, default=25)
    parser.add_argument("--trial-page-size", type=int, default=20)
    args = parser.parse_args()
    expand_knowledge_base(
        target_chunks=args.target_chunks,
        pubmed_retmax=args.pubmed_retmax,
        europepmc_page_size=args.europepmc_page_size,
        trial_page_size=args.trial_page_size,
    )


if __name__ == "__main__":
    main()
